/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'Reputation', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Reputation__factory>
getContractFactory(name: 'Request', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Request__factory>
getContractFactory(name: 'Roles', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Roles__factory>

  getContractAt(name: 'Reputation', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Reputation>
getContractAt(name: 'Request', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Request>
getContractAt(name: 'Roles', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Roles>

  deployContract(name: 'Reputation', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Reputation>
deployContract(name: 'Request', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Request>
deployContract(name: 'Roles', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Roles>

  deployContract(name: 'Reputation', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Reputation>
deployContract(name: 'Request', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Request>
deployContract(name: 'Roles', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Roles>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  