/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ReputationInterface extends Interface {
    getFunction(nameOrSignature: "award" | "owner" | "penalize" | "reputationOf" | "roles" | "setScore"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ReputationChanged" | "ReputationSet"): EventFragment;

    encodeFunctionData(functionFragment: 'award', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'penalize', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'reputationOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'roles', values?: undefined): string;
encodeFunctionData(functionFragment: 'setScore', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'award', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'penalize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reputationOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'roles', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setScore', data: BytesLike): Result;
  }

  
    export namespace ReputationChangedEvent {
      export type InputTuple = [who: AddressLike, by: AddressLike, justification: AddressLike, delta: BigNumberish, newScore: BigNumberish];
      export type OutputTuple = [who: string, by: string, justification: string, delta: bigint, newScore: bigint];
      export interface OutputObject {who: string, by: string, justification: string, delta: bigint, newScore: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReputationSetEvent {
      export type InputTuple = [who: AddressLike, by: AddressLike, oldScore: BigNumberish, newScore: BigNumberish];
      export type OutputTuple = [who: string, by: string, oldScore: bigint, newScore: bigint];
      export interface OutputObject {who: string, by: string, oldScore: bigint, newScore: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Reputation extends BaseContract {
    
    connect(runner?: ContractRunner | null): Reputation;
    waitForDeployment(): Promise<this>;

    interface: ReputationInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    award: TypedContractMethod<
      [who: AddressLike, justification: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    penalize: TypedContractMethod<
      [who: AddressLike, justification: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    reputationOf: TypedContractMethod<
      [who: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    roles: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setScore: TypedContractMethod<
      [who: AddressLike, newScore: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'award'): TypedContractMethod<
      [who: AddressLike, justification: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'penalize'): TypedContractMethod<
      [who: AddressLike, justification: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reputationOf'): TypedContractMethod<
      [who: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'roles'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setScore'): TypedContractMethod<
      [who: AddressLike, newScore: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ReputationChanged'): TypedContractEvent<ReputationChangedEvent.InputTuple, ReputationChangedEvent.OutputTuple, ReputationChangedEvent.OutputObject>;
getEvent(key: 'ReputationSet'): TypedContractEvent<ReputationSetEvent.InputTuple, ReputationSetEvent.OutputTuple, ReputationSetEvent.OutputObject>;

    filters: {
      
      'ReputationChanged(address,address,address,int256,int256)': TypedContractEvent<ReputationChangedEvent.InputTuple, ReputationChangedEvent.OutputTuple, ReputationChangedEvent.OutputObject>;
      ReputationChanged: TypedContractEvent<ReputationChangedEvent.InputTuple, ReputationChangedEvent.OutputTuple, ReputationChangedEvent.OutputObject>;
    

      'ReputationSet(address,address,int256,int256)': TypedContractEvent<ReputationSetEvent.InputTuple, ReputationSetEvent.OutputTuple, ReputationSetEvent.OutputObject>;
      ReputationSet: TypedContractEvent<ReputationSetEvent.InputTuple, ReputationSetEvent.OutputTuple, ReputationSetEvent.OutputObject>;
    
    };
  }