# CUDA base 
FROM nvidia/cuda:12.6.0-runtime-ubuntu22.04

# Basic deps
RUN apt-get update && apt-get install -y \
    python3 python3-pip python3-venv python3-dev git && \
    rm -rf /var/lib/apt/lists/*

# Create and "auto-activate" venv by placing it on PATH
# The break-system-packages is annoying, so i need to this to create venv which auto activates
ENV VENV_PATH=/opt/venv
RUN python3 -m venv $VENV_PATH
ENV PATH="$VENV_PATH/bin:$PATH"

# Install PyTorch with CUDA and deps inside venv
RUN pip install --no-cache-dir \
    torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126 \
    numpy
